# Generated by Django 4.1 on 2022-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id_aprendiz', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=128)),
                ('ficha', models.IntegerField()),
                ('fecha', models.DateField()),
                ('celular', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'aprendiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('clave', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=128)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
